version: '{build}'
skip_tags: true
image: Visual Studio 2017
clone_depth: 3
environment:
  AWS_ACCESS_KEY_ID:
    secure: 7jhk0oV/vjFsOcsAHLMUcNGUGLuGmnuPxGH0ce/Vky8=
  AWS_SECRET_ACCESS_KEY:
    secure: 5KKYpsIHwYHHh5ud0U7Ss0rLumv6G8tkS6abh1B9aq4wY6+1kq5fN/3E5BsdBVKy
  AWS_DEFAULT_REGION: us-east-1
  S3_CONFIG_VOLATILE: --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control "public, must-revalidate, proxy-revalidate, max-age=0"
  GIT_FORMAT: '%%H'
  matrix:
  - ARCH: x64
    BUILD: x64
    WIN: 64
    LIBNAME: bgfx.dll
  - ARCH: x86
    BUILD: Win32
    WIN: 32
    LIBNAME: bgfx32.dll
matrix:
  fast_finish: true
install:
- git clone https://github.com/LWJGL-CI/bx.git ../bx
- git clone https://github.com/LWJGL-CI/bimg.git ../bimg
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%

    ..\bx\tools\bin\windows\genie --with-shared-lib vs2017

    devenv .build\projects\vs2017\bgfx.sln /Project bgfx-shared-lib /Build "Release|%BUILD%"

    aws s3 cp .build/win%WIN%_vs2017/bin/bgfx-shared-libRelease.dll s3://build.lwjgl.org/nightly/windows/%ARCH%/%LIBNAME% %S3_CONFIG_VOLATILE%

    git log --pretty=format:%GIT_FORMAT% HEAD~2..HEAD~1 -1 > revision.git

    aws s3 cp revision.git s3://build.lwjgl.org/nightly/windows/%ARCH%/%LIBNAME%.git %S3_CONFIG_VOLATILE%
test: off
notifications:
- provider: Email
  to:
  - iotsakp@gmail.com
  subject: bgfx CI
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true